### ISSUE TITLE
Unable to enable service

### ISSUE THREAD

**Issue by poldolot** [christianfosli/msteams-notify-with-sound#1]
Hi @christianfosli 

What am I doing wrong?

![image](https://user-images.githubusercontent.com/5675282/222199748-8f148153-a630-4444-ad0b-866666d53977.png)

**Comment by christianfosli** [comment]
Hi. I'm by no means a systemd expert, but the first command there worked for me on Fedora Linux 37.

Could you try to copy the service file into ~/.config/systemd/user/, then run `systemctl --user enable msteams-notify`? (Like described here https://wiki.archlinux.org/title/Systemd/User )

**Comment by poldolot** [comment]
Thank You! It worked and I'm on Ubuntu 22.04 ;>
